name: Main CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  deploy_render:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.9

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev
      env:
        PIPENV_VENV_IN_PROJECT: 1

    - name: Trigger Render Deployment
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
      run: |
        echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> $GITHUB_ENV
        echo "PRIVATE_KEY_ID=${{ secrets.PRIVATE_KEY_ID }}" >> $GITHUB_ENV
        echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }}" >> $GITHUB_ENV
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
        echo "RENDER_API_TOKEN=${{ secrets.RENDER_API_TOKEN }}" >> $GITHUB_ENV
        pipenv run python render_deployment.py
