name: Main CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  deploy_render:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.9

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev
      env:
        PIPENV_VENV_IN_PROJECT: 1

    - name: Trigger Render Deployment
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: pipenv run python render_deployment.py
